### PR TITLE
Implementation with python3 boto3

### PR DESCRIPTION
**Pull request by yesimon**
Supports AWS Auth v4 and should be easier to maintain. However, since
there is no python3 boto3 debian/ubuntu package it's a bit difficult to
bootstrap. For now it has to be manually installed after

$ sudo pip3 install boto3

### CODE REVIEW

**Comment by vorlock** [comment]
I have 'kind a working' CoP for python3 but based on older version of boto and didn't do too much work on it lately.
I know that some guys are working on packaging boto3 for Debian, so I'll create separate branch for your work and we'll take it from there.

**Comment by vorlock** [comment]
python3-boto3 is now in Debian unstable (for 10 days) already so soon should be in testing.

**Comment by acaire** [comment]
Hi, can I suggest the following changes to keep Python2 support, remove the configobj requirement and insist that if users want to store custom credentials, they stick with [boto standards](http://boto3.readthedocs.org/en/latest/guide/configuration.html)?

https://github.com/yesimon/apt-transport-s3/compare/python3-boto3...cotdsa:python3-boto3

**Comment by vorlock** [comment]
Hi,

I actually have a problem with using boto for this transport. It isn't technical issue as such it's more around Debian minimal install size, integration, behaviour, etc. then anything else.

To use boto we would need to depend on it which for me is not the best option to have, that's why it's taking me so long to come to terms what shall we do with it.

IMO (I think) for such basic components we should try to avoid depending on any additional 'big'-ish libraries which would require installing.

**Comment by yesimon** [comment]
I think that's a fair point. Maybe the boto should be it's own repo as a different transport method.

**Comment by pcn** [comment]
https://github.com/BashtonLtd/apt-transport-s3/issues/22 is having me lean towards using the boto3+python3 implementation.  It does seem like having a separate name for that project would make sense.

**Comment by SonOfBytes** [comment]
I've added v4 sig capabilities to https://github.com/SonOfBytes/apt-transport-s3 - it's not a non breaking change but in the spirit of the original implementation and doesn't use boto.

I've also implemented a version in Go here - https://github.com/SonOfBytes/s3apt

All with minimalist testing.

**Comment by vorlock** [comment]
There are plans for porting s3 to python3 and right now we're testing authv4, so I'm closing this PR

**Pull request closed without merging**
